'use client';

import { useEffect } from 'react';

/**
 * Sends PageView event to CAPI on mount.
 * Uses the event_id generated by the inline Pixel script (window.__metaPageViewId)
 * so Meta can deduplicate between Pixel and CAPI.
 */
export function MetaPageViewCapi() {
  useEffect(() => {
    const eventId = window.__metaPageViewId;
    if (!eventId) return;

    const getCookie = (name: string) => {
      const match = document.cookie.match(new RegExp(`(?:^|; )${name}=([^;]*)`));
      return match ? decodeURIComponent(match[1]) : undefined;
    };

    fetch('/api/meta-capi', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        event_name: 'PageView',
        event_id: eventId,
        event_source_url: window.location.href,
        user_data: {
          fbp: getCookie('_fbp'),
          fbc: getCookie('_fbc'),
        },
      }),
      keepalive: true,
    }).catch(() => {});
  }, []);

  return null;
}
